"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-08-22 22:36:37.904023

Consolida en una sola migración: el esquema base (todas las tablas), el fix
de `preferred_theme` (ya declarado en el modelo pero nunca migrado por el
`_ensure_user_preference_columns()` ad-hoc que existía antes de Alembic), los
índices de `transactions`, el UNIQUE de `budgets` y los `nullable=False` en
las FKs de `transactions`. No hay usuarios reales todavía (ver
docs/specs/fase_07_spec.md, decisión 1.1.1), así que no hace falta separar
estos cambios en migraciones incrementales.

También incluye, como migración de datos, el paso legacy que antes vivía en
`seed_default_categories()` en `app/main.py`: renombrar "Otro (Gasto)" ->
"Otro" y fusionar "Otro (Ingreso)" en "Otro", reasignando transacciones y
presupuestos. Se ejecuta una sola vez aquí en vez de en cada arranque.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("preferred_currency", sa.String(length=3), nullable=True),
        sa.Column("preferred_locale", sa.String(length=10), nullable=True),
        sa.Column("preferred_theme", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("highlighted", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_id"), "accounts", ["id"], unique=False)
    op.create_index(op.f("ix_accounts_name"), "accounts", ["name"], unique=False)
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=False)
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount_limit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "category_id", "month", "year", name="uq_budgets_user_category_period"),
    )
    op.create_index(op.f("ix_budgets_id"), "budgets", ["id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transactions_account_id"), "transactions", ["account_id"], unique=False)
    op.create_index(op.f("ix_transactions_category_id"), "transactions", ["category_id"], unique=False)
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index("ix_transactions_user_id_date", "transactions", ["user_id", "date"], unique=False)
    # ### end Alembic commands ###

    _migrate_legacy_category_names()


def _migrate_legacy_category_names() -> None:
    """Migración de datos, una sola vez: reemplaza el paso legacy que antes
    corría en cada arranque dentro de app/main.py::seed_default_categories().

    - Renombra toda categoría "Otro (Gasto)" (type=expense) -> "Otro".
    - Fusiona toda categoría "Otro (Ingreso)" (type=income) en "Otro"
      (expense), reasignando sus transacciones/presupuestos y borrando la
      categoría "Otro (Ingreso)".

    Sobre una base de datos nueva (sin filas) esto es un no-op; se conserva
    para bases existentes que sí tuvieran esas categorías legacy.
    """
    bind = op.get_bind()

    categories = sa.table(
        "categories",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("type", sa.String),
        sa.column("user_id", sa.Integer),
    )
    transactions = sa.table(
        "transactions",
        sa.column("id", sa.Integer),
        sa.column("category_id", sa.Integer),
    )
    budgets = sa.table(
        "budgets",
        sa.column("id", sa.Integer),
        sa.column("category_id", sa.Integer),
    )

    # 1. Renombrar "Otro (Gasto)" -> "Otro" (sistema + por usuario).
    bind.execute(
        categories.update()
        .where(categories.c.name == "Otro (Gasto)")
        .where(categories.c.type == "expense")
        .values(name="Otro")
    )

    # 2. Fusionar "Otro (Ingreso)" en "Otro" (expense), por cada fila legacy.
    otros_ingreso = bind.execute(
        sa.select(categories.c.id, categories.c.user_id)
        .where(categories.c.name == "Otro (Ingreso)")
        .where(categories.c.type == "income")
    ).fetchall()

    for legacy_id, legacy_user_id in otros_ingreso:
        destino = bind.execute(
            sa.select(categories.c.id)
            .where(categories.c.name == "Otro")
            .where(categories.c.type == "expense")
            .where(categories.c.user_id == legacy_user_id)
        ).first()

        if destino is None and legacy_user_id is not None:
            destino = bind.execute(
                sa.select(categories.c.id)
                .where(categories.c.name == "Otro")
                .where(categories.c.type == "expense")
                .where(categories.c.user_id.is_(None))
            ).first()

        if destino is not None:
            destino_id = destino[0]
            bind.execute(
                transactions.update().where(transactions.c.category_id == legacy_id).values(category_id=destino_id)
            )
            bind.execute(budgets.update().where(budgets.c.category_id == legacy_id).values(category_id=destino_id))
            bind.execute(categories.delete().where(categories.c.id == legacy_id))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_user_id_date", table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_account_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_budgets_id"), table_name="budgets")
    op.drop_table("budgets")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_accounts_name"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
