"""fase_14_weekly_summary

Revision ID: 418c35db8cbc
Revises: 5a4a30ad3e77
Create Date: 2026-09-06 10:42:31.967988

Ítem 14.1 del spec docs/specs/fase_14_spec.md: columna `User.weekly_summary_enabled`
(opt-out, Decisión 14.1.1) + columna `Notification.period_key` (Decisión 14.1.2) + el
índice único parcial nuevo `uq_notifications_user_type_period_active` en la misma
migración (todos se declaran en sus `__table_args__`/modelo).

Revisada a mano tras `--autogenerate`:
- El índice PARCIAL `uq_notifications_user_type_period_active` se autogeneró
  correctamente con `postgresql_where`/`sqlite_where` (period_key IS NOT NULL) — NO hay
  que agregarlo a mano; verifica la unicidad "(user_id, type, period_key)" solo para
  filas con período semanal.
- `weekly_summary_enabled` es NOT NULL y se agrega como `server_default=sa.text('true')`
  para backfillear a los usuarios existentes al valor opt-out por defecto (Decisión
  14.1.1). El autogenerate no lo infiere (solo ve el `default` de Python del ORM, no un
  server_default); se agrega a mano siguiendo el criterio del skill alembic-migration
  para columnas NOT NULL nuevas sobre bases ya migradas.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "418c35db8cbc"
down_revision: str | None = "5a4a30ad3e77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("period_key", sa.String(length=10), nullable=True))
    op.create_index(
        "uq_notifications_user_type_period_active",
        "notifications",
        ["user_id", "type", "period_key"],
        unique=True,
        postgresql_where=sa.text("period_key IS NOT NULL"),
        sqlite_where=sa.text("period_key IS NOT NULL"),
    )
    op.add_column(
        "users", sa.Column("weekly_summary_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "weekly_summary_enabled")
    op.drop_index(
        "uq_notifications_user_type_period_active",
        table_name="notifications",
        postgresql_where=sa.text("period_key IS NOT NULL"),
        sqlite_where=sa.text("period_key IS NOT NULL"),
    )
    op.drop_column("notifications", "period_key")
    # ### end Alembic commands ###
